### ISSUE TITLE
A loading indicator

### ISSUE THREAD

**Issue by aborruso** [alessiodl/Leaflet.d3Layers#1]
Dear @alessiodl , I love your work!!

I think it would be useful to have something that informs the user that he must wait the loading of something (the data).

Thank you

**Comment by alessiodl** [comment]
Using a "loadend" event would do the trick (I'm going to add it to the classes), but the decision and the implementation of what to display before the data is loaded into the layer is up to the users. I'll give an example of this in the next release of the demo!
